version: "2"

services:
  buildfarm_redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
  server:
    build:
      context: .
    volumes:
      - ./config:/config
    ports:
      - 8980:8980

  worker:
    entrypoint: "/app/buildfarm-operationqueue-worker /config/worker.config"
    build:
      context: .
    volumes:
      - ./config:/config
    depends_on:
      - server
      


  # -- to add redis node..
